### ISSUE TITLE
HealthKeeper App Bluetooth Pairing Problem

### ISSUE THREAD

**Issue by Sumitlad** [shreshthtuli/FogBus#17]
Hi...
I have done all the steps present in User Manual but on opening HealthKeeper app and Pairing Device "Stop Application" Pop up appears and Pairing cancels...
I am Using BPL iOxy Pulse Oximeter.

**Comment by shreshthtuli** [comment]
https://github.com/shreshthtuli/FogBus/raw/master/Android-app/New-BLE/MIT-AppInventor/HealthKeeper_v3.apk

Please try with the latest app version from this link

**Comment by shreshthtuli** [comment]
This repository is now being managed as https://github.com/Cloudslab/FogBus

**Comment by Sumitlad** [comment]
> https://github.com/Cloudslab/FogBus/raw/master/Android-app/New-BLE/MIT-AppInventor/HealthKeeper_v3.apk
> 
> Please try with the latest app version from this link

![Screenshot_20190312-122348 1](https://user-images.githubusercontent.com/45627505/54328944-cf801700-4635-11e9-968d-7b86485634fe.png)
Sir i am already using v3.apk Please see the screenshot. Thank You.

**Comment by shreshthtuli** [comment]
As per my review of the BPL iOxy Pulse Oximeter, it communicates via unicode 32 encoding. Please check the following v4 of the HealthKeeper app which works for unicode 32. 
https://github.com/Cloudslab/FogBus/raw/master/Android-app/New-BLE/MIT-AppInventor/HealthKeeper_v4.apk

**Comment by Sumitlad** [comment]
Hello sir i just tried V4.apk but problem is occurring during Pairing of bluetooth.
![WhatsApp Image 2019-04-05 at 12 07 07 PM](https://user-images.githubusercontent.com/45627505/55608597-65721200-579c-11e9-9dfd-a7018f9fce82.jpeg)
![WhatsApp Image 2019-04-05 at 12 07 07 PM](https://user-images.githubusercontent.com/45627505/55608610-6acf5c80-579c-11e9-9597-3ea5eded15a3.jpeg)

See the attachments

**Comment by shreshthtuli** [comment]
Please try with the apk attached
[HealthKeeper_v5.zip](https://github.com/shreshthtuli/FogBus/files/3047205/HealthKeeper_v5.zip)

**Comment by Sumitlad** [comment]
Sir, Again the same error is appearing while recording data is started.... after 15-27 sec. this error appears..
![Screenshot_20190405-154708](https://user-images.githubusercontent.com/45627505/55621186-729df980-57ba-11e9-9cd4-1514cb61bd34.png)

**Comment by shreshthtuli** [comment]
The oximeter you are using is faulty IMHO.
Please try with this version of the app but some reading may be invalid.
[HealthKeeper_v6.zip](https://github.com/shreshthtuli/FogBus/files/3051911/HealthKeeper_v6.zip)

**Comment by Sumitlad** [comment]
Can you please suggest any device so I can perform the test. Or tell me name of device which are you using

**Comment by shreshthtuli** [comment]
The oximeter: Jumper JPD-500F Finger Pulse Oximeter, 1.5V, Bluetooth Low Energy v4.2 (BLE)
Has been we tested and works with FogBus. BPL oxy that you are using should also work but the piece you have may be faulty.

**Comment by Sumitlad** [comment]
Sir actually this device you mentioned is not available for purchase... its old and not available in stock so can you please suggest me any other device?

**Comment by shreshthtuli** [comment]
I tried to test BPL iOxy with HealthKeeper_v6.zip sent to you. It works fine in the following mode:
![20190415_195809](https://user-images.githubusercontent.com/34661516/56140786-325c2980-5fb9-11e9-930b-3f20235c2c46.jpg)

**Comment by Sumitlad** [comment]
Can you please tell me the Smartphone brand which ur using for testing? OS? & model?

**Comment by shreshthtuli** [comment]
It is samsung galaxy s7, android 9

**Comment by Sumitlad** [comment]
Ok sir i'll test it today.. One more question.... Is it possible to implement this environment without connecting to Aneka/Azure Cloud? On local setup just by eliminating part of cloud?

**Comment by shreshthtuli** [comment]
Yes, you can disable Aneka in the config.txt file in master where HealthKeeper is installed.

**Comment by Sumitlad** [comment]
Sir i have tested v6 apk with my bpl ioxy.. its working fine getting results but ECG graph is not showing. whether ECG graph module work with aneka only?
![Screenshot_2019-05-14-10-23-57-360_appinventor ai_shreshthtuli HealthKeeper_v3](https://user-images.githubusercontent.com/45627505/57672452-d0352980-7635-11e9-9fb5-2a229b299d99.png)
![Screenshot_2019-05-14-10-23-50-291_appinventor ai_shreshthtuli HealthKeeper_v3](https://user-images.githubusercontent.com/45627505/57672453-d0cdc000-7635-11e9-97eb-00ee62ae07e0.png)

**Comment by shreshthtuli** [comment]
Glad that it worked out finally. No, there should be ECG in the webpage. Did you try to scroll down?
