### ISSUE TITLE
Cannot run Android app for project

### ISSUE THREAD

**Issue by talk2bryan** [shreshthtuli/FogBus#19]
Using Android Studio 3.3.1, I attempted to run the app to replicate your research but had over 2,000 compile errors. It seems impossible to debug. Pls, advise on what steps to take.

I dumped the results from the compilation errors [here](https://dumptext.com/DjKXhty2).

**Comment by shreshthtuli** [comment]
There are some problems in the Java version of the app. Please use MIT's App Inventor to modify and compile the code.
